export const types = Object.freeze({
  GENERATE: "PLANET::GENERATE",
  SET_OWNER: "PLANET::SET_OWNER",
  SET_SHIPS: "PLANET::SET_SHIPS",
  ADJUST_SHIPS: "PLANET::ADJUST_SHIPS",
  PRODUCE: "PLANET::PRODUCE",
});
